name: ADD A CHANGELOG ENTRY
on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update changelog
        run: |
          fullBranchName=${{github.event.pull_request.head.ref}}
          typeOfPr=$(echo "$fullBranchName" | awk -F'/' '{print $1}')
          second=$(echo "$fullBranchName" | awk -F'/' '{print $2}')
          prGitNum=${{github.event.number }}
          jiraTicketNumber = 	$(echo "$typeOfPr" | cut -d '-' -f 2)
          # xtypeOfPr=$(echo "${{github.event.pull_request.head.ref}}" | cut -d '/' -f 1)
          # cleanBranchName=$(echo "${{github.event.pull_request.head.ref}}" | cut -d '/' -f 2)
          echo $jiraTicketNumber
          # echo $xtypeOfPr
          # echo $cleanBranchName

          # target branch = base_ref
          # source branch = head_ref
          if [ $GITHUB_BASE_REF == 'main' ]; then
          	searchBranchName="## Main"
          elif [ $GITHUB_BASE_REF == 'develop' ]; then
          	searchBranchName="## Development"
          else
          	searchBranchName=""
          fi


          if [ $typeOfPr == "FEA" ]; then
            # if [[ -z $second ]]; then
            #   echo "SECOND IS EMPTY"
            # fi
            searchTypeOfPr="### Added"
          elif [ $typeOfPr == 'ESR' ]; then
          	searchTypeOfPr="### Fixed"
          elif [ $typeOfPr == 'HOT' ]; then
          	searchTypeOfPr="### Fixed"
          else
            searchTypeOfPr="NOT_FOUND"
          fi
          # echo $example



          #check if the PR title has a JIRA ticket number at the beginning
          jira_pattern="[0-9]+"
          if [[ $prGitNum =~ ^$jira_pattern ]]; then
            jira_link="https://ecoonline.atlassian.net/browse/${second}-${prGitNum}"
          else
            jira_link=""
          fi


          first_changelog_entry="\* [["${typeOfPr}/${second}-${prGitNum}"]](${jira_link})"
          second_changelog_entry="[Pull #${{ github.event.number }}](${{ github.event.pull_request.html_url }}) ${{ github.event.pull_request.title }}"

          # echo ${searchBranchName}
          # echo ${first_changelog_entry}
          # echo ${second_changelog_entry}
          sed "/^${searchBranchName}/,/^${searchTypeOfPr}/!b;/^${searchTypeOfPr}/!b;:a;n;/./ba;i${first_changelog_entry} ${second_changelog_entry}" CHANGELOG.md > CHANGELOG.md.new

          mv CHANGELOG.md.new CHANGELOG.md
          git add CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Updated CHANGELOG for PR #${prGitNum}"
          git push