name: MINE OH MINE
on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]
env:
  SLAV : Slaven
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initial Stuff done
        run: |
          pr_pod_name=$(echo "${{ github.event.pull_request.title }}" | cut -d '-' -f 1)
          pr_number=$(echo "${{ github.event.pull_request.title }}" | cut -d '-' -f 2)


          #check if the PR title has a JIRA ticket number at the beginning
          #jira_pattern="[A-Z]+\-[0-9]+"
          jira_pattern="[0-9]+"
          if [[ $pr_number =~ ^$jira_pattern ]]; then
            jira_ticket="${BASH_REMATCH[0]}"
            jira_link="https://ecoonline.atlassian.net/browse/${pr_pod_name}-${jira_ticket}"

          else
            jira_link=""
          fi

          changelog_entry="\* [["FEA/${pr_pod_name}-${jira_ticket}"]](${jira_link})"
          echo ${changelog_entry}

          sed '/^## Main/,/^### Fixed/!b;/^### Fixed/!b;:a;n;/./ba;iNew line to be inserted' CHANGELOG.md > CHANGELOG.md.new

          mv CHANGELOG.md.new CHANGELOG.md
          git add CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update CHANGELOG for PR #${pr_number}"
          git push