name: MINE OH MINE
on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]
env:
  PR_TITLE: ${{ github.event.pull_request.title }}
  PR_URL: ${{ github.event.pull_request.url }}
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initial Stuff done
        run: |
          # pr_number=$(echo "${{ github.event.pull_request.url }}" | cut -d / -f 7)
          # pr_title="${{ github.event.pull_request.title }}"
          # echo "apple;banana;cherry" | cut -d ';' -f 1
          # echo "$MY_NAME_IS"
          echo $PR_TITLE
          echo $PR_URL
          PR_NUMBER = ($PR_TITLE | cut -d / -f 2)
          echo PR_NUMBER