name: Add a changelog entry
on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update changelog file
        run: |
          fullBranchName=${{github.event.pull_request.head.ref}}
          typeOfPr=$(echo "$fullBranchName" | awk -F'/' '{print $1}')
          second=$(echo "$fullBranchName" | awk -F'/' '{print $2}')
          prGitNum=${{github.event.number }}
          podsName=$(echo "$second" | cut -d '-' -f 1)
          jiraTicketNumber=$(echo "$second" | cut -d '-' -f 2)
          if [ $GITHUB_BASE_REF == 'main' ]; then
          	searchBranchName="## Main"
          elif [ $GITHUB_BASE_REF == 'develop' ]; then
          	searchBranchName="## Development"
          else
          	searchBranchName=""
          fi
          if [ $typeOfPr == "FEA" ]; then
            searchTypeOfPr="### Added"
          elif [ $typeOfPr == 'ESR' ]; then
          	searchTypeOfPr="### Fixed"
          elif [ $typeOfPr == 'HOT' ]; then
          	searchTypeOfPr="### Fixed"
          else
            searchTypeOfPr="NOT_FOUND"
          fi
          jira_pattern="[0-9]+"
          if [[ $prGitNum =~ ^$jira_pattern ]]; then
            jira_link="https://ecoonline.atlassian.net/browse/${podsName}-${jiraTicketNumber}"
          else
            jira_link=""
          fi

          first_changelog_entry="\* [["${typeOfPr}/${podsName}-${jiraTicketNumber}"]](${jira_link})"
          second_changelog_entry="[Pull #${{ github.event.number }}](${{ github.event.pull_request.html_url }}) ${{ github.event.pull_request.title }}"
          sed "/^${searchBranchName}/,/^${searchTypeOfPr}/!b;/^${searchTypeOfPr}/!b;:a;n;/./ba;i${first_changelog_entry} ${second_changelog_entry}" CHANGELOG.md > CHANGELOG.md.new

          mv CHANGELOG.md.new CHANGELOG.md
          git add CHANGELOG.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Updated CHANGELOG for PR #${prGitNum}"
          git push -f




