name: ADD A CHANGELOG ENTRY
on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update changelog
        env:
          token: ${{secrets.REPO_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          fullBranchName=${{github.event.pull_request.head.ref}}
          typeOfPr=$(echo "$fullBranchName" | awk -F'/' '{print $1}')
          second=$(echo "$fullBranchName" | awk -F'/' '{print $2}')
          prGitNum=${{github.event.number }}
          podsName=$(echo "$second" | cut -d '-' -f 1)
          jiraTicketNumber=$(echo "$second" | cut -d '-' -f 2)

          # target branch = base_ref
          # source branch = head_ref
          if [ $GITHUB_BASE_REF == 'main' ]; then
          	searchBranchName="## Main"
          elif [ $GITHUB_BASE_REF == 'develop' ]; then
          	searchBranchName="## Development"
          else
          	searchBranchName=""
          fi

          if [ $typeOfPr == "FEA" ]; then
            # if [[ -z $second ]]; then
            # fi
            searchTypeOfPr="### Added"
          elif [ $typeOfPr == 'ESR' ]; then
          	searchTypeOfPr="### Fixed"
          elif [ $typeOfPr == 'HOT' ]; then
          	searchTypeOfPr="### Fixed"
          else
            searchTypeOfPr="NOT_FOUND"
          fi

          #check if the PR title has a JIRA ticket number at the beginning
          jira_pattern="[0-9]+"
          if [[ $prGitNum =~ ^$jira_pattern ]]; then
            jira_link="https://ecoonline.atlassian.net/browse/${podsName}-${jiraTicketNumber}"
          else
            jira_link=""
          fi

          first_changelog_entry="\* [["${typeOfPr}/${podsName}-${jiraTicketNumber}"]](${jira_link})"
          second_changelog_entry="[Pull #${{ github.event.number }}](${{ github.event.pull_request.html_url }}) ${{ github.event.pull_request.title }}"

          sed "/^${searchBranchName}/,/^${searchTypeOfPr}/!b;/^${searchTypeOfPr}/!b;:a;n;/./ba;i${first_changelog_entry} ${second_changelog_entry}" CHANGELOG.md > CHANGELOG.md.new

          mv CHANGELOG.md.new CHANGELOG.md
          git add CHANGELOG.md
          git config --local user.email "slaven@biome.net"
          git config --local user.name "Slaven Saka"
          git commit -m "Updated CHANGELOG for PR #${prGitNum}"
          git push

      - name: Notify Teams Channel
        uses: jdcargile/ms-teams-notification@v1.3
        with:
            github-token: ${{ github.token }} # this will use the runner's token.
            ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
            notification-summary: ${{ github.event.pull_request.title }}
            notification-color: 17a2b8
            timezone: Europe/Dublin
