name: MINE OH MINE
on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]
env:
  SLAV : Slaven
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initial Stuff done
        run: |
          PR_POD_NAME = $(echo "${{ github.event.pull_request.title }}" | cut -d '-' -f 1)
          PR_NUMBER = $(echo "${{ github.event.pull_request.title }}" | cut -d '-' -f 2)
          echo $PR_POD_NAME
          echo $PR_NUMBER